pool:
  name: MyAgentPool

steps:
- task: DotNetCoreCLI@2
  inputs:
    packageType: 'sdk'
    version: '3.x' # You should specify the desired .NET Core SDK version here
    command: 'build'

- bash: echo hello world
